version: '3'

services:
  web:
    container_name: "moto_sol_project"
    image: docker.io/benonymus/elixir_docker_1.9
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DATABASE_URL=ecto://postgres:postgres@postgres/moto_sol_project_dev
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    links:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
